name: Daily Pipeline

on:
  schedule:
    - cron: "30 14 * * *"   # 8:00 PM IST
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger daily pipeline
        run: |
          curl -X POST "${{ secrets.PIPELINE_URL}}" \
            -H "Authorization: Bearer ${{ secrets.PIPELINE_TOKEN }}" \
            -H "Content-Type: application/json"